packages:
  - apps/*
  - modules/*
  - packages/*

catalog:
  "@tanstack/react-query": "5.64.2"
  "@types/lodash": "4.14.182"
  "@types/react": "19.0.8"
  "@types/react-dom": "19.0.3"
  "bignumber.js": "9.1.2"
  "classnames": "2.3.2"
  "dayjs": "1.11.13"
  "lodash": "4.17.21"
  "react": "19.0"
  "react-dom": "19.0"
  "react-router": "7.1.3"
  "tailwindcss": "^4.0.4"

catalogs:
  react18:
    "@types/react": "18.0"
    "@types/react-dom": "18.0"
    "react": "18.0"
    "react-dom": "18.0"

  react-router6:
    "react-router": "6.14.1"
    "react-router-dom": "6.14.1"
