packages:
  - apps/*
  - packages/*
  - infra/*
  - examples/*

catalog:
  '@rsbuild/plugin-less': '2.0.1'
  '@rsbuild/plugin-react': '2.1.0'
  '@rsbuild/plugin-source-build': '1.0.6'
  '@rsbuild/plugin-svgr': '2.0.5'
  '@rsbuild/core': '2.1.5'
  '@rslib/core': '0.23.2'
  '@rstest/adapter-rsbuild': '0.11.1'
  '@rstest/adapter-rslib': '0.11.1'
  '@rstest/coverage-istanbul': '0.11.1'
  '@rstest/core': '0.11.1'
  '@testing-library/jest-dom': '6.9.1'
  '@hono/node-server': '2.0.9'
  '@hono/zod-openapi': '1.5.1'
  '@scalar/hono-api-reference': '0.11.9'
  '@types/node': '22'
  '@types/better-sqlite3': '7.6.13'
  'better-sqlite3': '12.11.1'
  'drizzle-kit': '0.31.10'
  'drizzle-orm': '0.45.2'
  'glob': '13.0.6'
  'happy-dom': '20.10.6'
  'hono': '4.12.30'
  'husky': '9.1.7'
  'jsdom': '29.1.1'
  'lint-staged': '17.0.8'
  'oxfmt': '0.59.0'
  'oxlint': '1.74.0'
  'postcss': '8.5.19'
  'rsbuild-plugin-devtools-json': '1.0.1'
  'stylelint': '17.14.0'
  'stylelint-config-standard': '40.0.0'
  'stylelint-less': '4.2.1'
  'tsx': '4.23.1'
  'typescript': '7.0.2'
  'zod': '4.4.3'
  'zustand': '5.0.14'
